name: Set up WireGuard Connection

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  wireguard:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up WireGuard Connection
      uses: niklaskeerl/easy-wireguard-action@v2
      with:
        WG_CONFIG_FILE: ${{ secrets.WG_CONFIG_FILE }}
    - name: Start connection WireGuard
      run: |
        sudo wg-quick up wg0
    - name: Test Connection
      run: |
        ping -c 4 10.9.0.1
