name: WireGuard wg1

on:
  workflow_dispatch:

jobs:
  wireguard_example:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install wireguard

      - run: echo "${{ secrets.WG_CONFIG_FILE }}" > wg0.conf

      - run: sudo chmod 600 wg0.conf
          
      - run: sudo wg-quick up ./wg0.conf

      - run: ping -c 4 10.9.0.1

      - run: curl -vvv -m 30 http://192.168.11.136

      - run: sudo wg-quick down wg0
