name: WireGuard wg0

on:
  workflow_dispatch:

jobs:
  wireguard_connection:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Wireguard connection
        run: |
          sudo apt install wireguard
          echo "${{ secrets.WIREGUARD_CLIENT_PRIVATE_KEY }}" > privatekey
          sudo ip link add dev wg0 type wireguard
          sudo ip address add dev wg0 "${{ secrets.WIREGUARD_CLIENT_ADDRESS }}"
          sudo wg set wg0 listen-port 48123 private-key privatekey peer "${{ secrets.WIREGUARD_SERVER_PUBLIC_KEY }}" allowed-ips 0.0.0.0/0 endpoint "${{ secrets.WIREGUARD_SERVER_ENDPOINT }}"
          sudo ip link set up dev wg0
          sudo ip route add 192.168.11.0/24 dev wg0
          sudo sed -i 's/#DNS=/DNS=192.168.11.102/g' /etc/systemd/resolved.conf
          sudo systemctl daemon-reload
          sudo systemctl restart systemd-networkd
          sudo systemctl restart systemd-resolved
          echo "nameserver 192.168.11.102" |  sudo tee  /etc/resolv.conf.DNSoverride
          sudo ln -sf /etc/resolv.conf.DNSoverride /etc/resolv.conf
          cat /etc/resolv.conf 
          ping -c 4 10.9.0.1
          nslookup awx.root.sx
      - name: Invoke a webhook to AWX
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.AWX_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.AWX_WEBHOOK_SECRET }}
