name: WireGuard wg1

on:
  workflow_dispatch:

jobs:
  wireguard_example:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install wireguard

      - run: echo "${{ secrets.WIREGUARD_CLIENT_PRIVATE_KEY }}" > privatekey

      - run: sudo ip link add dev wg0 type wireguard

      - run: sudo ip address add dev wg0 "${{ secrets.WIREGUARD_CLIENT_ADDRESS }}" peer 10.9.0.1

      - run: sudo wg set wg0 listen-port 48123 private-key privatekey peer "${{ WIREGUARD_SERVER_PUBLIC_KEY }}" allowed-ips 0.0.0.0/0 endpoint "${{ secrets.WIREGUARD_SERVER_ENDPOINT }}"

      - run: sudo ip link set up dev wg0

      - run: curl -vvv http://192.168.11.136

      - run: sudo wg-quick down wg0
