name: WireGuard Connection

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  connect:
    runs-on: ubuntu-latest

    steps:
      - name: Install WireGuard
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard
          sudo touch /etc/wireguard/wg1.conf

      - name: Configure WireGuard
        run: |
          echo "[Interface]" > wg1.conf
          echo "PrivateKey = ${{ secrets.WIREGUARD_CLIENT_PRIVATE_KEY }}" >> wg1.conf
          echo "Address = ${{ secrets.WIREGUARD_CLIENT_ADDRESS }}/24" >> wg1.conf
          echo "" >> wg1.conf
          echo "[Peer]" >> wg1.conf
          echo "PublicKey = ${{ secrets.WIREGUARD_SERVER_PUBLIC_KEY }}" >> wg1.conf
          echo "Endpoint = ${{ secrets.WIREGUARD_SERVER_ENDPOINT }}" >> wg1.conf
          echo "AllowedIPs = ${{ secrets.WIREGUARD_SERVER_ALLOWED_IPS }}" >> wg1.conf
          sudo wg-quick up wg1

      - name: Test Connection
        run: |
          ping -c 4 10.9.0.1
      - name: Wireguard Down
        run: |
          sudo wg-quick down wg1
