name: WireGuard Connection

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  connect:
    runs-on: ubuntu-latest

    steps:
      - name: Install WireGuard
        run: |
          sudo apt-get install -y wireguard

      - name: Configure WireGuard
        run: |
          echo "${{ secrets.WG_CONFIG_FILE }}" > wg0.conf
          sudo chmod 600 wg0.conf
          sudo wg-quick up ./wg0.conf
          ping -c 4 10.9.0.1
          sudo wg-quick down wg0
          ping -c 4 10.9.0.1
          curl -vvv -m 30 http://192.168.11.136
          sudo wg-quick down wg0
        shell: bash
